import Link from "next/link";
import Image from "next/image";
import { Flex, Box, Text, Button } from "@chakra-ui/react";
import Head from "next/head";

const Banner = ({imageUrl, purpose, title, title2, linkName, buttonText, desc1, desc2 }:any) => {
  return (
    <>
      <Flex flexWrap="wrap" justifyContent="center" alignItems="center" m="10">
        <Image
        src={imageUrl}
        width = "500"
        height={300}
        alt="banner"
        />

        <Box
        p={5}
        >
          <Text color={"gray.500"} fontSize="sm" fontWeight={"medium"}>
            {purpose}
          </Text>

          <Text fontSize="3xl" fontWeight={"bold"}>
            {title} <br /> {title2}
          </Text>  
          
           <Text fontSize="lg" color={"gray.700"} paddingBottom="3" paddingTop={5}>
            {desc1} <br /> {desc2}
          </Text>

          <Button fontSize={"xl"} bg="blue.300" color={"white"}>
            <Link href={linkName}>{buttonText}</Link>
          </Button>

        </Box>
      </Flex>
    </>
  );
};

export default function Home() {
  return (
    <>
      <Head>
        <title>Real Estate API Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Hello World</h1>
        <Banner text={"text"} />
      </main>
    </>
  );
}
